# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e64b9af597531824e11b047610e69c21be74876e4f360919c4ddeab13d3d28abe4242959462d21d8dc60e0fbc586ff6b4aa0299b57eb7663283144030808f60

test:
  secret_key_base: cd270346c2a7598564b0857db150cbc57a8dce3ee923cfa8c4cad687fb53e5f41b1a726bd7af497ad6a1920037a4f70b67de9bb741c3df9a799fa05b73370bc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
